### ISSUE TITLE
Overflow items deleted

### ISSUE THREAD

**Issue by Shmeeb** [CJcool06/SafeTrade#10]
Either make items that cannot fit into a user's inv after a trade be spit onto the ground, or don't allow the trade to go through at all (nucleus's kits feature has some good code for this)

**Comment by VOrlando520** [comment]
Believe CJ all but abandoned this, if I were you, id fork it and apply the fixes yourself. Unsure of the licenses for a public release edit but.

**Comment by CJcool06** [comment]
All overflow items are placed in the player's `/safetrade storage` in the latest version.
