### ISSUE TITLE
Error occured while executing command: null

### ISSUE THREAD

**Issue by ghost** [CJcool06/SafeTrade#14]
Im using safetrade-1.12.2-2.0.5-Sponge
And when i go to invite someone to a trade and they hit accept it returns this
Error occured while executing command: null

I gave players perm safetrade.common.* and admins safetrade.admin.*

**Comment by CJcool06** [comment]
I need a stacktrace to locate the problem.

**Comment by LaiZBoi** [comment]
Im am also getting this error. 
https://pastebin.com/bHiZ1MZJ

**Comment by SmallSansSerif** [comment]
Same error. Please advise.
