### ISSUE TITLE
Pause Safetrade

### ISSUE THREAD

**Issue by RandomMelonHere** [CJcool06/SafeTrade#3]
I believe pausing a Safetrade is currently bugged. I tried to pause safetrade and well it did, but I could not figure out how to un-pause it. I tried doing /safetrade (player) since that just reopens the trade but it gave me the message "You cannot safetrade with a player that is already in a safetrade!" This also means whatever items in the safetrade should just be stuck inside it, without being able to get it out.

Can't tell whether this is a bug or there is just a specific way to unpause. Either way, a reply would be very much appreciated.

**Comment by CJcool06** [comment]
To resume a SafeTrade use `/safetrade open`. I accidentally forgot to add that to the wiki, oops!

**Comment by RandomMelonHere** [comment]
Thank you! This helped a lot :)
