### ISSUE TITLE
Restart Resulting In Lost Pixelmon

### ISSUE THREAD

**Issue by HeyWinkeyFace** [CJcool06/SafeTrade#6]
If you're engaged in a safetrade and the server closes/crashes all of the pixelmon are lost.

**Comment by CJcool06** [comment]
Can't reproduce this doing normal server stops. Everything in the trade will be lost if the server crashes without Sponge being able to handle the game stopping appropriately, so that may be why you experienced this. If you are able to reproduce this, reopen this issue.
