### ISSUE TITLE
Confirmation screen not showing correct money

### ISSUE THREAD

**Issue by SnowBlitzz** [CJcool06/SafeTrade#7]
For example if you put 7k in the trade and go to confirm it, it will show 0. The person will still receive the money fine so it's just the display that is wrong.

**Comment by CJcool06** [comment]
What version are you using

**Comment by SnowBlitzz** [comment]
I'm using the latest `1.12.2-2.0.3-PIXELMON`

**Comment by CJcool06** [comment]
Fixed for next release.
