### ISSUE TITLE
Money glitch

### ISSUE THREAD

**Issue by Shmeeb** [CJcool06/SafeTrade#9]
When you add money then go into the second section after readying up it comes up as you've added no money until you ready up. https://i.imgur.com/r3KQSor.png https://i.imgur.com/qgR1JAG.png

Using `SafeTrade-1.12.2-2.0.4-PIXELMON.jar`

**Comment by Trnrr** [comment]
I have another issue with this. 2 profiles each had $100 and 1 profile traded the other $100 while the other traded $0. The one who traded nothing ended up with $300 and the other ended up with $100. Anyway to disable money?

**Comment by CJcool06** [comment]
Fixed in latest version.
